import type { Recommendation, ScanResult, SimulationResult } from "../types.js";

/** Markdown / JSON report rendering — the "proof layer" of pgHeal. */

export function proofTable(sim: SimulationResult): string {
  const pct = (x: number | null) => (x === null ? "n/a" : `${(100 * (1 - x)).toFixed(1)}%`);
  const cost = (x: number | null) => (x === null ? "n/a" : x.toFixed(1));
  const speedup = (x: number | null) => (x === null ? "n/a" : `${x.toFixed(1)}x`);
  return [
    "| Metric | Before | After (hypothetical) |",
    "|---|---|---|",
    `| Plan node | ${sim.before.nodeType} | ${sim.after?.nodeType ?? "n/a"} |`,
    `| Total cost | ${cost(sim.before.totalCost)} | ${cost(sim.after?.totalCost ?? null)} |`,
    `| Estimated rows | ${sim.before.planRows} | ${sim.after?.planRows ?? "n/a"} |`,
    `| Cost reduction | — | ${pct(sim.costRatio)} |`,
    `| Speedup factor | — | ${speedup(sim.speedup)} |`,
    `| Est. index size | — | ${sim.estimatedIndexSizeBytes ? humanBytes(sim.estimatedIndexSizeBytes) : "n/a"} |`,
  ].join("\n");
}

export function renderReport(scan: ScanResult): string {
  const lines: string[] = [];
  lines.push(`# pgHeal Scan Report`);
  lines.push("");
  lines.push(`- **Database:** ${scan.db.database} · **Server:** ${scan.db.serverVersion.split(",")[0]}`);
  lines.push(`- **HypoPG:** ${scan.db.hypopg ? "✅ available (proven mode)" : "❌ not installed (unproven mode)"}`);
  lines.push(`- **pg_stat_statements:** ${scan.db.pgss ? "✅" : "❌"}`);
  lines.push("");

  if (scan.recommendations.length === 0 && scan.cleanup.drops.length === 0) {
    lines.push("> No proven improvements found. Your workload looks well-indexed. 🎉");
    return lines.join("\n");
  }

  if (scan.recommendations.length > 0) {
    lines.push(`## Proven index recommendations (${scan.recommendations.length})`);
    lines.push("");
    scan.recommendations.forEach((rec, i) => {
      const sim = rec.simulation;
      lines.push(`### ${i + 1}. \`${sim.candidate.table}\` → (${sim.candidate.columns.join(", ")})`);
      lines.push("");
      lines.push(`- **Reason:** ${sim.candidate.reason}`);
      lines.push(`- **Query (normalized, truncated):**`);
      lines.push("```sql");
      lines.push(rec.simulation.candidate.fromQueryid ? truncate(candidateQuery(scan, rec), 400) : "");
      lines.push("```");
      lines.push("");
      lines.push(proofTable(sim));
      lines.push("");
      lines.push("```sql");
      lines.push(rec.migration.content.trim());
      lines.push("```");
      lines.push("");
    });
  }

  if (scan.cleanup.drops.length > 0) {
    lines.push(`## Index cleanup candidates (${scan.cleanup.drops.length})`);
    lines.push("");
    lines.push("| Index | Table | Reason | Size | Est. write overhead/day |");
    lines.push("|---|---|---|---|---|");
    for (const d of scan.cleanup.drops) {
      lines.push(
        `| \`${d.index.name}\` | ${d.index.table} | ${d.reason}${d.supersededBy ? ` (by \`${d.supersededBy}\`)` : ""} | ${humanBytes(d.index.sizeBytes)} | ${humanBytes(d.writeOverheadPerDay)} |`,
      );
    }
    lines.push("");
    lines.push("> ⚠️ DROP suggestions require a 30+ day observation window (idx_scan=0 since last stats reset).");
    lines.push("");
  }

  if (scan.warnings.length > 0) {
    lines.push(`## Warnings`);
    lines.push("");
    for (const w of scan.warnings) lines.push(`- ⚠️ ${w}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by pgHeal — zero data exfiltration: only normalized query fingerprints and catalog statistics were used._",
  );
  return lines.join("\n");
}

function candidateQuery(scan: ScanResult, rec: Recommendation): string {
  const stmt = scan.candidates.find((c) => c.statement.queryid === rec.simulation.candidate.fromQueryid);
  return stmt?.statement.query ?? "(query unavailable)";
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n) + "…" : s;
}

export function humanBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 ** 3) return `${(n / 1024 ** 2).toFixed(1)} MB`;
  return `${(n / 1024 ** 3).toFixed(2)} GB`;
}

export function reportToJson(scan: ScanResult): string {
  return JSON.stringify(
    {
      db: scan.db,
      recommendations: scan.recommendations.map((r) => ({
        table: r.simulation.candidate.table,
        columns: r.simulation.candidate.columns,
        accepted: r.simulation.accepted,
        speedup: r.simulation.speedup,
        costRatio: r.simulation.costRatio,
        ddl: r.migration.content.trim(),
      })),
      cleanup: {
        drops: scan.cleanup.drops.map((d) => ({
          index: d.index.name,
          table: d.index.table,
          reason: d.reason,
          sizeBytes: d.index.sizeBytes,
        })),
        totalWriteOverheadBytesPerDay: scan.cleanup.totalWriteOverheadBytesPerDay,
      },
      warnings: scan.warnings,
    },
    null,
    2,
  );
}
