/**
 * Dual-package rendering — one report for both halves of the "DB + contract
 * security" conversation, in the same voice as pgHeal's own scan report.
 *
 * Zero data exfiltration carries over unchanged: the kanıt's findings are
 * already public by construction (a kanıt is a claim of discovery, not a
 * paywalled preimage), and pgHeal's side carries only normalized fingerprints
 * and catalog statistics.
 */

import type { DualPackage, UnifiedSeverity } from "./types.js";

const SEVERITY_BADGE: Record<UnifiedSeverity, string> = {
  critical: "🔴 critical",
  high: "🟠 high",
  medium: "🟡 medium",
  low: "🔵 low",
  info: "ℹ️ info",
};

/** Markdown report of the dual package — the artifact a customer reads. */
export function renderDualReport(pkg: DualPackage): string {
  const lines: string[] = [];
  lines.push("# pgHeal × AegisForge — Dual Security Package");
  lines.push("");
  lines.push(`- **Package id:** \`${pkg.id}\``);
  lines.push(`- **Schema:** \`${pkg.schema}\``);
  lines.push("");
  lines.push(gateBlock(pkg));
  lines.push("");

  lines.push("## Contract half — AegisForge");
  lines.push("");
  const c = pkg.contract;
  lines.push(`- **Engine:** ${c.engine} ${c.engineVersion}`);
  lines.push(`- **Kanıt hash:** ${c.kanitHash === null ? "—" : "`" + c.kanitHash + "`"}`);
  lines.push(`- **Merkle root:** ${c.merkleRoot === null ? "—" : "`" + c.merkleRoot + "`"}`);
  lines.push(`- **Signer:** ${c.signer === null ? "—" : "`" + c.signer + "`"}`);
  lines.push(`- **Chain id:** ${c.chainId === null ? "—" : c.chainId}`);
  lines.push(
    `- **Hash gates (recomputed in TypeScript):** ${c.hashGatesOk ? "✅ Merkle root + kanıt hash re-verify" : "❌ FAILED — findings treated as unverified claims"}`,
  );
  lines.push("");

  if (c.findings > 0) {
    lines.push("| Severity | Count |");
    lines.push("|---|---|");
    for (const sev of ["critical", "high", "medium", "low"] as const) {
      lines.push(`| ${SEVERITY_BADGE[sev]} | ${c.severityCounts[sev]} |`);
    }
    lines.push("");
  } else {
    lines.push("> No contract findings in this package.");
    lines.push("");
  }

  lines.push("## Database half — pgHeal");
  lines.push("");
  const d = pkg.database;
  lines.push(`- **Proven index recommendations:** ${d.proven}`);
  lines.push(`- **Grounded (not HypoPG-simulable):** ${d.grounded}`);
  lines.push(`- **Cleanup candidates:** ${d.cleanupCandidates}`);
  lines.push(
    `- **Best proven speedup:** ${d.bestSpeedup === null ? "—" : `${d.bestSpeedup.toFixed(1)}x`}`,
  );
  lines.push("");

  if (pkg.findings.length > 0) {
    lines.push("## Unified findings (most severe first)");
    lines.push("");
    lines.push("| # | Source | Severity | Finding | Proof |");
    lines.push("|---|---|---|---|---|");
    pkg.findings.forEach((f, i) => {
      const where = f.locator.contract
        ? `\`${f.locator.contract}\`.\`${f.locator.function ?? "?"}\``
        : f.locator.index
          ? `index \`${f.locator.index}\``
          : `\`${f.locator.table ?? "?"}\` (${(f.locator.columns ?? []).join(", ")})`;
      lines.push(
        `| ${i + 1} | ${f.source} | ${SEVERITY_BADGE[f.severity]} | **${f.title}** — ${escapeMd(f.detail)} (${where}) | ${proofBadge(f.proofStatus)} |`,
      );
    });
    lines.push("");
  } else {
    lines.push("> No findings from either oracle — both halves are clean.");
    lines.push("");
  }

  if (pkg.notes.length > 0) {
    lines.push("## Notes");
    lines.push("");
    for (const n of pkg.notes) lines.push(`- ℹ️ ${n}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by pgHeal's contract-twin bridge — the kanıt hash gates are recomputed from the published fields; the secp256k1 signature and address gates are verified by `aegisforge verify`. Zero data exfiltration on the database side: only normalized fingerprints and catalog statistics._",
  );
  return lines.join("\n");
}

function gateBlock(pkg: DualPackage): string {
  const head = pkg.gate.decision === "act" ? "🚦 **act** — both oracles delivered proof" :
    pkg.gate.decision === "review" ? "🚦 **review** — one oracle delivered proof, the other supplied evidence" :
    "🚦 **clean** — nothing actionable from either oracle";
  const lines = ["> " + head, ">"];
  for (const r of pkg.gate.reasons) lines.push(`> - ${r}`);
  return lines.join("\n");
}

function proofBadge(status: string): string {
  switch (status) {
    case "signed-kanit":
      return "✅ kanıt (hash gates green)";
    case "hypopg-proven":
      return "✅ HypoPG-proven";
    case "grounded":
      return "🟡 grounded, not proven";
    case "hash-mismatch":
      return "❌ hash mismatch";
    default:
      return "⚫ unproven";
  }
}

function escapeMd(s: string): string {
  return s.replace(/\|/g, "\\|");
}

/** JSON serialization of the dual package (the machine-readable twin of the report). */
export function dualPackageToJson(pkg: DualPackage): string {
  return JSON.stringify(pkg, null, 2);
}
